### ISSUE TITLE
No recibo una response correcta

### ISSUE THREAD

**Issue by Deme94** [altipla-consulting/redsys-golang#13]
Hola

Me gustaria poder ver un ejemplo real en un entorno de prueba para ver que funciona, porque aquí no se está enviando ninguna petición http.

He seguido la guía oficial y mando un post con el signature, parameters, etc, pero la response devuelve un html erróneo. ¿Habéis confirmado que esta librería realmente funciona con redsys?

Gracias y un saludo

**Comment by ernestoalejo** [comment]
Buenas, la usamos en producción. Si me permites viendo el primer ejemplo antes de editar la issue creo que el fallo está en la integración, te comento cómo funciona. Los pasos serían aproximadamente los siguientes:

1. Necesitas previamente la información que te da el banco para integrar en pruebas (ID de comercio, etc.).

2. Con esta librería se firman los datos (el nombre del comercio, la cantidad a pagar y demás) generando 3 cadenas de texto (Signature, SignatureVersion y Params). También devuelve la URL según sea el entorno de pruebas o de producción.

3. Se mandan los datos con el navegador. Atención aquí que creo que es dónde está el fallo. La petición POST debe mandarla el navegador, no el código de Go. Puedes hacerlo con una etiqueta `<form>` que te da el banco de ejemplo. Nosotros lo hacemos con Javascript:

```js
// DOM manipulation to create a fake form that we can send to the
// remote POST endpoint of the bank network.
let form = document.createElement('form')
form.setAttribute('method', 'POST')
form.setAttribute('action', params.url)

let input = document.createElement('input')
input.setAttribute('type', 'hidden')
input.setAttribute('name', 'Ds_SignatureVersion')
input.value = params.signatureVersion
form.appendChild(input)

input = document.createElement('input')
input.setAttribute('type', 'hidden')
input.setAttribute('name', 'Ds_Signature')
input.value = params.signature
form.appendChild(input)

input = document.createElement('input')
input.setAttribute('type', 'hidden')
input.setAttribute('name', 'Ds_MerchantParameters')
input.value = params.params
form.appendChild(input)
document.body.appendChild(form)

form.submit()
```

4. Cuando el usuario termina de pagar vuelve a la URL del callback con unos parámetros. Con esta librería puedes verificar la firma y leer el contenido con lo que ha pagado, si ha cancelado, si faltaba dinero en la tarjeta, etc.

**Comment by ernestoalejo** [comment]
He añadido un apartado de Usage en el readme para completar la respuesta un poco más y tener los pasos un poco más detallados. Entre otras cosas he vinculado también una página que te puede venir bien para comprenderlo (https://pagosonline.redsys.es/conexion-redireccion.html).

Cualquier duda adicional que te podamos aclarar del proceso me dices.

**Comment by Deme94** [comment]
Muchas gracias, te avisaré cuando lo probemos.
Sí, casi seguro que la parte que estaba mal era la del envío del post. Probaremos a enviarlo desde el navegador de esa manera.

Gracias, un saludo

**Comment by Deme94** [comment]
Hola Ernesto,
Está funcionando a la perfección. 
Muchas gracias por desarrollar la librería. 
El apartado Usage es un lujo, mejor que la guía oficial.

Un abrazo de un almeriense
